# https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: '3.5'
services:
  voipd:
    image: flaviostutz/freepbx
    environment:
      - ADMIN_PASSWORD=admin123
      - FAIL2BAN_ENABLE=false
    container_name: "voipd"
    volumes:
      - ./../data/backup:/backup
      - ./../data/recordings:/var/spool/asterisk/monitor
    restart: always
    ports:
      - 8080:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 3306:3306
      - 18000-18100:18000-18100/udp
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
